/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "fourBitRCA.v:1" *)
module fourBitRCA(clk, rst_n, A, B, Cin, Sum, Cout);
  (* src = "fourBitRCA.v:29" *)
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "fourBitRCA.v:4" *)
  input [3:0] A;
  (* src = "fourBitRCA.v:11" *)
  wire [3:0] A_reg;
  (* src = "fourBitRCA.v:5" *)
  input [3:0] B;
  (* src = "fourBitRCA.v:11" *)
  wire [3:0] B_reg;
  (* src = "fourBitRCA.v:6" *)
  input Cin;
  (* src = "fourBitRCA.v:12" *)
  wire Cin_reg;
  (* src = "fourBitRCA.v:8" *)
  output Cout;
  (* src = "fourBitRCA.v:7" *)
  output [3:0] Sum;
  (* src = "fourBitRCA.v:2" *)
  input clk;
  (* src = "fourBitRCA.v:13" *)
  wire [4:0] result;
  (* src = "fourBitRCA.v:3" *)
  input rst_n;
  sky130_fd_sc_hd__xnor2_1 _08_ (
    .A(A_reg[2]),
    .B(B_reg[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(A_reg[0]),
    .B(B_reg[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(A_reg[0]),
    .B(B_reg[0]),
    .C(Cin_reg),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _11_ (
    .A(A_reg[1]),
    .B(B_reg[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(A_reg[1]),
    .B(B_reg[1]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__maj3_1 _13_ (
    .A(A_reg[2]),
    .B(B_reg[2]),
    .C(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(A_reg[3]),
    .B(B_reg[3]),
    .C(_06_),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(Cin_reg),
    .B(_02_),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(_03_),
    .B(_04_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(_01_),
    .B(_05_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(A_reg[3]),
    .B(B_reg[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(_06_),
    .B(_07_),
    .Y(_00_[3])
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(result[0])
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(result[1])
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(result[2])
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(result[3])
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfxtp_1 _24_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(result[4])
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk),
    .D(result[0]),
    .Q(Sum[0]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk),
    .D(result[1]),
    .Q(Sum[1]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(clk),
    .D(result[2]),
    .Q(Sum[2]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(clk),
    .D(result[3]),
    .Q(Sum[3]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:29" *)
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(clk),
    .D(result[4]),
    .Q(Cout),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(clk),
    .D(Cin),
    .Q(Cin_reg),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _31_ (
    .CLK(clk),
    .D(B[0]),
    .Q(B_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clk),
    .D(B[1]),
    .Q(B_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(B[2]),
    .Q(B_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(B[3]),
    .Q(B_reg[3]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(A[0]),
    .Q(A_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(A[1]),
    .Q(A_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(A[2]),
    .Q(A_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "fourBitRCA.v:16" *)
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(A[3]),
    .Q(A_reg[3]),
    .RESET_B(rst_n)
  );
endmodule
